name: Build application

on:
  - push
  - pull_request

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build go
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        run: |
          go test -coverpkg=./... -coverprofile="coverage.out"
          go build -ldflags="-s -w" -a -tags netgo -o app .
      - name: Save build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app
          retention-days: 1
  image:
    runs-on: ubuntu-latest
    needs:
      - app
    steps:
      - uses: actions/checkout@v2

      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app

      - name: Give binary perm
        run: chmod +x app

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: github.actor!= 'dependabot[bot]' # ignore the pull request which comes from user depbot.
